apiVersion: v1
kind: Service
metadata:
  name: reacthelloworld
spec:
  selector:
    app: reacthelloworld
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reacthelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reacthelloworld
  template:
    metadata:
      labels:
        app: reacthelloworld
    spec:
      containers:
        - name: reacthelloworld
          image: ablaamim/simlab-react-nginx
          ports:
            - containerPort: 80
          imagePullPolicy: Always

