apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: default  # Ensure the namespace is specified
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31880  # Ensure the NodePort is set
