apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default  # Ensure the namespace is specified
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: nginx
          command:
            - /bin/sh
            - -c
            - "echo 'Modification pushed!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
          ports:
            - containerPort: 80
          imagePullPolicy: Always


